// Integrations module exports

export * from './types';

// Gmail exports
export {
  // Types
  type GmailTokens,
  type GmailCredentials,
  type GmailUserInfo,
  type GmailHeader,
  type GmailMessagePart,
  type GmailMessage,
  type GmailMessageMetadata,
  type GmailListResponse,
  type GmailThread,
  type GmailLabel,
  type Email,
  type EmailAttachment,
  type EmailDraft,
  type EmailListOptions,
  type GmailOAuthState,
  GMAIL_LABELS,
  GMAIL_SCOPES,
  // Auth
  getGoogleAuthUrl,
  exchangeCodeForTokens as exchangeGmailCodeForTokens,
  refreshAccessToken as refreshGmailAccessToken,
  getUserInfo as getGmailUserInfo,
  revokeToken,
  saveGmailAuth,
  loadGmailAuth,
  clearGmailAuth,
  isTokenExpired as isGmailTokenExpired,
  getValidAccessToken as getValidGmailAccessToken,
  getCredentials as getGmailCredentials,
  isGmailConnected,
  getConnectedEmail,
  // Client
  listMessages,
  getMessage,
  getThread,
  searchEmails,
  sendEmail,
  replyToEmail,
  markAsRead,
  markAsUnread,
  starMessage,
  unstarMessage,
  trashMessage,
  deleteMessage,
  listLabels,
  getUnreadCount,
  batchGetMessages,
} from './gmail';

// Calendar exports
export {
  // Types
  type CalendarTokens,
  type CalendarCredentials,
  type CalendarUserInfo,
  type CalendarEvent,
  type EventDateTime,
  type EventAttendee,
  type EventReminder,
  type EventAttachment,
  type ConferenceData,
  type CalendarListEntry,
  type EventListResponse,
  type FreeBusyResponse,
  type SimpleEvent,
  type EventDraft,
  type EventUpdateDraft,
  type EventListOptions,
  type FreeTimeSlot,
  type CalendarOAuthState,
  CALENDAR_SCOPES,
  // Auth
  getGoogleCalendarAuthUrl,
  exchangeCodeForTokens as exchangeCalendarCodeForTokens,
  refreshAccessToken as refreshCalendarAccessToken,
  getUserInfo as getCalendarUserInfo,
  revokeToken as revokeCalendarToken,
  saveCalendarAuth,
  loadCalendarAuth,
  clearCalendarAuth,
  isTokenExpired as isCalendarTokenExpired,
  getValidAccessToken as getValidCalendarAccessToken,
  getCredentials as getCalendarCredentials,
  isCalendarConnected,
  getConnectedCalendarEmail,
  // Client
  listCalendars,
  getPrimaryCalendar,
  listEvents,
  getUpcomingEvents,
  getTodayEvents,
  getEventsInRange,
  getEvent,
  searchEvents,
  createEvent,
  quickAddEvent,
  updateEvent,
  deleteEvent,
  getFreeBusy,
  findFreeTime,
  getEventCount,
  isTimeSlotAvailable,
} from './calendar';
